### ISSUE TITLE
Calendar events merged

### ISSUE THREAD

**Issue by dberntsson** [heskja/MMM-CalendarWeek#1]
I have two different calendars (google ical files) where the same event (same title and the same starttime).

Only one of these events are listed and presented on my MagicMirror.

Expected behaviour is to have two events presented since they are not the same (different calendar origins)

**Comment by heskja** [comment]
Oops, wrong commit

**Comment by heskja** [comment]
This is by design and also identical behavior as the original calendar module in MagicMirror.

I have however added the config option `allowDuplicate: true` to allow for duplicate events. Please feel free to test it.

**Comment by dberntsson** [comment]
Works like a charm! Thanks!
