### ISSUE TITLE
Distance between days

### ISSUE THREAD

**Issue by mhermens123** [heskja/MMM-CalendarWeek#15]
I want only two days to display, but they are very far apart from each other.
is there a way to put them next to each other?
settings:
maximumDaysPerLine = 2
maximumNumberOfDays = 2

**Comment by heskja** [comment]
Have you tried setting `hideEmptyDays` = true?

**Comment by mhermens123** [comment]
Yes, it looks like this:
https://imgur.com/a/OxKRx4k
config file:
				displaySymbol: false,
				maximumNumberOfDays: "2",
				hideEmptyDays: true,
				dateFormat: "dddd",
				tableClass: "xsmall",

**Comment by heskja** [comment]
What module position have you set?

**Comment by mhermens123** [comment]
module position is bottom_center

**Comment by mhermens123** [comment]
day is not centered:
https://imgur.com/a/3XrD08R

**Comment by heskja** [comment]
I can't seem to reproduce the behavior you are describing. Would you mind sharing the entire config so I can see whats going on?

**Comment by heskja** [comment]
Closed due to missing feedback
