### ISSUE TITLE
How to display 2 or more calendars

### ISSUE THREAD

**Issue by Jorgeceballosso** [heskja/MMM-CalendarWeek#17]
How is possible to mix 2 or more calendars with different symbol ?

### I already try to mix 3 methods 
calendars: [
		{
			url: 'URL 1.ics',
			symbol: 'calendar',
                        url: 'URL 2.ics',
			symbol: 'briefcase',
			},
	],

### also I try 

calendars: [
		{
			url: 'URL 1.ics',
			symbol: 'calendar',
			auth: {
			}
		},
	],
calendars: [
		{
			url: 'URL 2.ics',
			symbol: 'calendar',
			}
		},
	],

### Finally i Try 

config: {
	colored: false,
	coloredSymbolOnly: false,
	calendars: [
		{
			url: 'URL 1.ics',
			symbol: 'calendar',
			}
		},
	],
}

config: {
	colored: false,
	coloredSymbolOnly: false,
	calendars: [
		{
			url: 'URL 2.ics',
			symbol: 'calendar',

			}
		},
	],
}

I know that there is something wrong, maybe you can help me to fix it.

Thanks

**Comment by heskja** [comment]
No response, I assume the question has been resolved.
