### ISSUE TITLE
Show more then 4 days don't show events after 4 days

### ISSUE THREAD

**Issue by Bernieinc** [heskja/MMM-CalendarWeek#19]
When I use maximumNumberOfDays to show 7 days. Only events 4 days in the future is shown. I can see all the 7 days in the calender, but after 4 days no events are shown even there are event in the calender. Do I need to do something more the just insert maximumNumberOfDays: 7, under config
It is my google calender I use in the module 

thanks for help

**Comment by heskja** [comment]
Hi,
Could you please post your entire config for this module? The parameter `maximumEntries` may also be a limiting factor, as this defaults to 20.

**Comment by Bernieinc** [comment]
Hi 

I tried with maximumEntries now and it did not work. I have tried to add more event in 4 day period and that works. but after 4 days the will not show. thanks again for help

{
			module: "MMM-CalendarWeek",
			position: "middle_center",
			config: {
			colored: "true",
			maximumNumberOfDays: 7,
			maximumEntries: 100,
				calendars: [
					{
			url: "https://calendar.google.com/calendar/ical/bernhard.stahre%40gmail.com/public/basic.ics",
			symbol: "calendar",
			}
			]
			
			}
		},

**Comment by heskja** [comment]
Seems like this is related to how MagicMirror handles the loading of helper modules. Restarting MagicMirror seems to increase the number of days loaded. Could you please restart your MagicMirror and verify this?

**Comment by Bernieinc** [comment]
Yes that worked fine. I was using pm2 start and it did not work to just close the magic mirror and the pm2 started it again.  I did a full rebot of the rasberry and nog it works. Thanks for all help!
