### ISSUE TITLE
Multiple days scales bad

### ISSUE THREAD

**Issue by dberntsson** [heskja/MMM-CalendarWeek#2]
My screen can handle 6-7 days without scaling is affected.
If I want more than one week listed, the days are presented "outside of the screen".
Could it be possible to have multiple lines of days when presenting that amount of days?

**Comment by heskja** [comment]
You will have to manually specify the number of days per line. Please feel free to test this by using config option `maximumDaysPerLine: 7` if you have more than one week of events.
