### ISSUE TITLE
Google calendar not showing up.

### ISSUE THREAD

**Issue by fritzaj4** [heskja/MMM-CalendarWeek#21]
So I have had this setup for multiple months with 2 different google calendars updating and showing perfectly fine. Today, my main calendar just disappeared and would not show after multiple attempts. I tried changing the iCal to public, reset the private iCal, and I replaced my other calendar's slot with it, but nothing worked. I am extreme beginner at all of this, it was kind of a struggle to set everything, so I may struggle to understand things. Thanks so much in advance!!

**Comment by heskja** [comment]
hi,
Sorry for the late response.
Could you please provide config file for your setup? I am using Google calendar in my own setup, and have no confirmed issues with Google calendar using private iCal.

**Comment by GenericArt** [comment]
I'm experiencing the same problem. If I switch over to the default "calendar" the feed comes in fine with a provate ical. My config:

{
		module: "MMM-CalendarWeek",
		position: "center_middle",	// This can be any of the regions. Best results in bottom region.
    config: {
    	colored: false,
    	coloredSymbolOnly: false,
    	calendars: [
    		{
    			url: 'https://calendar.google.com/calendar/ical/#######.ics',
    			symbol: 'calendar',
    			
    		},
    	],
    }
}

**Comment by heskja** [comment]
Closed due to lack of feedback
