### ISSUE TITLE
Feature Request:  Calendar Header/Title

### ISSUE THREAD

**Issue by DaveDischord** [heskja/MMM-CalendarWeek#24]
Would it be possible to add a Calendar Title above the calendar, for instance, if you have 2 calendars, one for Birthdays, and one for Special Events in different positions, in order to distinguish them.

**Comment by heskja** [comment]
I'll look into this, but don't think it would be too much work. Just need to make it look good :) Any ideas on how you would like this to be presented?

**Comment by DaveDischord** [comment]
I'm thinking it could just be top, bold, and center above the calendar.
Maybe it could also be able to have a symbol, in case it's a single-themed
calendar.

**Comment by heskja** [comment]
Something like the Google-text shown in this image? (sorry for the Norwegian language)
![Pasted_Image_25_04_2019__20_08](https://user-images.githubusercontent.com/7541932/56758062-f9307000-6795-11e9-9bea-1ef3ae643f81.png)

**Comment by DaveDischord** [comment]
I bet that'd be perfect for standard use.

**Comment by heskja** [comment]
Thanks, pushed it into production now.
