### ISSUE TITLE
Local iCal file

### ISSUE THREAD

**Issue by Stant0n** [heskja/MMM-CalendarWeek#25]
Is there a method to access a locally stored calendar file, instead of an internet one?

**Comment by heskja** [comment]
Have you tried the solution proposed from forum member Shockwave here?
https://forum.magicmirror.builders/topic/467/calendar-ics-file-from-local-path

**Comment by Stant0n** [comment]
I haven’t tried. But I will. 
Thank you

**Comment by heskja** [comment]
I'll close the issue, but please feel free to reopen it if you need further assistanse.
