### ISSUE TITLE
Center rows in column for proper alignment

### ISSUE THREAD

**Issue by Muffexx** [heskja/MMM-CalendarWeek#32]
Hello, I really enjoy using your MagicMirrorModule.

While there are requests to provide some kind of table layout, which could be achieved by simply adding "border: 1px solid white;" to the .col element in the css file, I'm curious on how to align the rows within each column.

When using a border you can see that all columns (up to three) in a row are aligned to the left (except the date) side which leads to irregular distances between each day.

Maybe someone can provide adivice. Maybe this improvement would refer to #28.

regards.

**Comment by Muffexx** [comment]
Well, it took me like six hours to figure it out, but in the end this works:

col.setAttribute("align","center");

It has to be added within the MMM-CalendarWeek.js after the var col has been created (line 254).

Maybe somebody wants to add this and make it configurable from within the config.js

regards.

**Comment by nickosouras** [comment]
> Well, it took me like six hours to figure it out, but in the end this works:
> 
> col.setAttribute("align","center");
> 
> It has to be added within the MMM-CalendarWeek.js after the var col has been created (line 254).
> 
> Maybe somebody wants to add this and make it configurable from within the config.js
> 
> regards.

could you elaborate on how you get everything centered?

**Comment by Muffexx** [comment]
I'm unsure about what to additionally explain.
After I set the attribute of the column it got aligned as intened.
Sorry if this isn't what you've been looking for.
