### ISSUE TITLE
Stuck in loading...

### ISSUE THREAD

**Issue by IceT-max** [heskja/MMM-CalendarWeek#38]
Loading  the module is still in "Caricamento in corso".. (loading in english I suppose) and nothing appears.

That is my config, and pay attention: with default calendar module all works correctly...

{
                module: "MMM-CalendarWeek",
                position: "bottom_bar", // This can be any of the regions. Best results in bottom region.
config: {
        colored: false,
        coloredSymbolOnly: false,
        calendars: [
                {
                        url: '"https://calendar.google.com/calendar/ical/.........',
                        symbol: 'calendar',
                },
        ],
}
},

Any ideas? Pay attention that I use the module from a remote server in cloud.

**Comment by heskja** [comment]
So you are saying that if you change from 'module: "MMM-CalendarWeek"' to 'module: "calendar" it all works..?

**Comment by IceT-max** [comment]
Yes, using same parameters. In calendar I don't use the authentication and see all events; but there no. 🤔

**Comment by vexter0944** [comment]
Had similar issue - calendar and MMM-CalendarWeek would not work and just say loading until I rebooted my pi each time after switched module in config.js.  Might not be the same issue, but wanted to post.  Good luck!

**Comment by heskja** [comment]
Unable to reproduce the issue. Will close for now.
