### ISSUE TITLE
Days without events still take horizontal space

### ISSUE THREAD

**Issue by dberntsson** [heskja/MMM-CalendarWeek#5]
When I have dates that doesn't have any events, it seems like the space is still reserved in the UI.
This will generate unnecessary space between the date columns.

**Comment by heskja** [comment]
This is by design, as I would like  to know if I am available/have no plans for the day.

You can however test the feature using config option `hideEmptyDays: true` in your MagicMirror configuration. Please feel free to give me your feedback.

**Comment by dberntsson** [comment]
Thank you! Works just fine!
