### ISSUE TITLE
Calendar only says, "No Schedules" :(

### ISSUE THREAD

**Issue by bezwe** [heskja/MMM-CalendarWeek#50]
Hi everyone,

I actually don't know anything about programming, but the Magic Mirror is something I got really interested in.

I added the module using the terminal and also made the necessary adjustments on the config.js, just as @heskja instructed. Unfortunately, I am not getting any results. At the bottom part, it only says, "No Schedules (keine Termine)". What am I doing wrong?

I would absolutely appreciate any help I can get.

**Comment by alexbergsland** [comment]
Post the MMM-CalendarWeek part from config.js here using 'Instert Code' tags.

For reference, my google calendar looks like this:
```
                {
                        module: "MMM-CalendarWeek",
                        position: "top_left",
                        config: {
                                maximumNumberOfDays: "2",
                                displayLocation: true,
                                showEndDate: true,
                                maximumDaysPerLine: "1",
                                maximumEntries: "7",
                                calendars: [
                                        {
                                                symbol: "calendar",
                                                url: "https://calendar.google.com/calendar/ical/my_secret_adress_in.ics"
                                        }
                                ]
                        }
                },
```

It only shows stuff from the next two days.

**Comment by bezwe** [comment]
> Post the MMM-CalendarWeek part from config.js here using 'Instert Code' tags.
> 
> For reference, my google calendar looks like this:
> 
> ```
>                 {
>                         module: "MMM-CalendarWeek",
>                         position: "top_left",
>                         config: {
>                                 maximumNumberOfDays: "2",
>                                 displayLocation: true,
>                                 showEndDate: true,
>                                 maximumDaysPerLine: "1",
>                                 maximumEntries: "7",
>                                 calendars: [
>                                         {
>                                                 symbol: "calendar",
>                                                 url: "https://calendar.google.com/calendar/ical/my_secret_adress_in.ics"
>                                         }
>                                 ]
>                         }
>                 },
> ```
> 
> It only shows stuff from the next two days.

I found the error! :) Thank you for the reference! I added the wrong URL.

Cheers!
