### ISSUE TITLE
Upgrade to MM v2.16 breaks this 

### ISSUE THREAD

**Issue by je4928** [heskja/MMM-CalendarWeek#53]
[12.07.2021 11:04.20.344] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'rrule-alt'
Require stack:
- /home/pi/MagicMirror/modules/MMM-CalendarWeek/vendor/ical.js/node-ical.js
- /home/pi/MagicMirror/modules/MMM-CalendarWeek/vendor/ical.js/index.js
- /home/pi/MagicMirror/modules/MMM-CalendarWeek/calendarfetcher.js
- /home/pi/MagicMirror/modules/MMM-CalendarWeek/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js

I tried fix in other issue post for v2.16 and it does not fix.

**Comment by gabrielmc9** [comment]
I had a similar " Could not load config file" error upgrading to MM 2.16.  The `valid-url` fix didn't work.  I rolled back to 2.15.

**Comment by je4928** [comment]
Issued the following and it is now working..

npm install rrule-alt
npm install valid-url
